// Placeholder for bundled transcripts (generated by scripts/bundle-transcripts.ts)
// In static mode, this file is replaced with actual data

import type { TranscriptDisplayFull, TranscriptDisplayMeta } from '$lib/shared/types';

export const BUNDLED_TRANSCRIPTS: Record<string, TranscriptDisplayFull> = {};

export const TRANSCRIPT_LIST_METADATA: TranscriptDisplayMeta[] = [];

export const BUNDLE_GENERATED_AT = '';
export const BUNDLE_TRANSCRIPT_COUNT = 0;
